sudo: required
dist: trusty
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install dpkg-dev dh-python python-setuptools python3-setuptools python3-all debhelper quilt polipo lighttpd
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.3.0.deb && sudo service elasticsearch start
  - pip install -r REQUIREMENTS
  - for file in intelmq/bots/*/*/REQUIREMENTS.txt; do pip install -r $file; done
  - if [[ $TRAVIS_PYTHON_VERSION < '3.5' ]]; then pip install typing; fi
  - pip install codecov
  - pip install pycodestyle
  - sudo pip install .
  - sudo cp /opt/intelmq/etc/examples/* /opt/intelmq/etc/
before_script:
  - psql -c "CREATE USER intelmq WITH SUPERUSER" -U postgres
  - psql -c "CREATE DATABASE intelmq" -U intelmq template1
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE intelmq TO intelmq" -U intelmq
  - intelmq_psql_initdb
  - sed -i 's/events/tests/g' /tmp/initdb.sql
  - psql -v ON_ERROR_STOP=on -f /tmp/initdb.sql intelmq -U intelmq
script:
  - INTELMQ_TEST_DATABASES=1 INTELMQ_TEST_LOCAL_WEB=1 INTELMQ_TEST_EXOTIC=1 nosetests --with-coverage --cover-package=intelmq
  - dpkg-buildpackage -us -uc
  - pycodestyle intelmq/{bots,lib,bin}
services:
  - redis-server
  - postgresql
  - elasticsearch
  - mongodb
after_success:
  - codecov
addons:
  postgresql: "9.4"
